apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "inventory.name" . }}-db
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.secretName }}"
        objectType: "secretsmanager"
        objectAlias: "{{ .Values.secrets.fileName }}"
